### ISSUE TITLE
Move to signed ordinals?

### ISSUE THREAD

**Issue by aprokop** [ORNL-CEES/DataTransferKit#206]
What are pros and cons?

**Comment by Rombur** [comment]
I found a nice article about it https://kristerw.blogspot.de/2016/02/how-undefined-signed-overflow-enables.html Like people say in the comment while these optimizations are possible most of them shouldn't make any big difference (Also some optimizations are only possible with `unsigned int` http://stackoverflow.com/questions/4712315/performance-of-unsigned-vs-signed-integers). The main advantage seems that it helps the compiler to vectorize loops. I guess that could be pretty important for us since Kokkos doesn't let you annotate a loop to force vectorization :-( If you want to use vectorization you either change some flags in Kokkos so the compiler is more aggressive or you need to use a three level nested parallelism and that's really ugly.

**Comment by aprokop** [comment]
Mark has some interesting thoughts (here)[https://groups.google.com/forum/#!topic/trilinos/ruXNsFQ-1K4]. Of particular importance:
```
GlobalOrdinal is not a trivial template parameter, like T in std::vector<T>.  I can't just allow any old type there.  If I allow a type, I need to test it regularly in order to make sure it works.  If I happen to allow some unsigned GlobalOrdinal types, it's only because some key user insisted upon it.  They are responsible for maintaining and testing those types.  Unsigned GlobalOrdinal types are NOT enabled by default. 
```

**Comment by aprokop** [comment]
Another one against unsigned: no support in Fortran, so no robust interoperability.

**Comment by aprokop** [comment]
I would like to resurrect this discussion. We need to decide on what to instantiate on when moving to Trilinos as TPL. In addition, as Trilinos moves to signed 64-bit global ordinals, is there a reason not to follow it there?

**Comment by dalg24** [comment]
Can't think of any reason atm.

**Comment by sslattery** [comment]
Neither can I.
