### ISSUE TITLE
Investigate and Unit Test CUDA-Aware MPI

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#224]
A unit test (or tests) are needed to demonstrate and protect supported CUDA-aware MPI capabilities. This test should allow for basic MPI operations directly with `Kokkos::View` objects.

**Comment by sslattery** [comment]
This needs to be resolved to address #222

**Comment by Rombur** [comment]
Because of UVM, there is no need for a unit test. We can always write the code like we had CUDA-aware MPI. Instead, we want to monitor the performance hit of not using CUDA-aware MPI. We can use the code from #234 to write a code that checks the performance. We need to check that we can build OpenMPI with CUDA in a container that does not have CUDA yet. Otherwise, we need to install CUDA in the base container instead of adding CUDA during `docker-compose build`.
