### ISSUE TITLE
error with GETRF with MLS

### ISSUE THREAD

**Issue by jeff788** [ORNL-CEES/DataTransferKit#309]
Hi,

I'm a relatively new DTK user, but have used it successfully on one project and am now using it on other. I am using DTK 2.0 (2.0.0-5-g63d2fc8) and I am interpolating from one point cloud to another using the following parameters:

```c++
 m_parameters = rcp(new ParameterList("DataTransferKit"));
  m_parameters->set("Map Type",
                   "Point Cloud");

  ParameterList& pc_params = m_parameters->sublist("Point Cloud", false);
  pc_params.set("Map Type",
                "Moving Least Square Reconstruction");
  pc_params.set("Basis Type",
                "Wendland");
  pc_params.set("Basis Order",
                0);
   pc_params.set("Spatial Dimension",
                3);
   pc_params.set("Type of Search",
                 "Nearest Neighbor");
  pc_params.set("Num Neighbors",
                8);
```

This worked well with one data set, but now it is crashing with the following error:
```
terminate called after throwing an instance of 'DataTransferKit::DataTransferKitException'
  what():  DataTransferKit DataTransferKitException: 0 == info, failed in /home/burg137/build/Trilinos/DataTransferKit/packages/Operators/src/PointCloud/DTK_LocalMLSProblem_impl.hpp, line 168.
```
I have attached a commented gdb log. I understand that this is caused by an LU factorization returning with a zero on the diagonal of U. I printed out the coordinates of the target and the eight source points, and everything looks okay to me. I also did this for points with a successful LU factorization and didn't see anything obviously different. Any help would be appreciated.

Thanks,

Jeff

[gdb_log_commented.txt](https://github.com/ORNL-CEES/DataTransferKit/files/1357441/gdb_log_commented.txt)

**Comment by jeff788** [comment]
I read this paper 

https://www.casl.gov/sites/default/files/docs/CASL-U-2015-0177-000.pdf

and now understand (I think) that it is related to the linear dependence of the position vectors of the source points. Right? I increased the number of nearest neighbours from 8 to 10 and it seems to have fixed the problem. Is there a more robust set of parameters/algorithms that I could be using? I'm interpolating from the centroids of a structured finite difference grid to the centroids of an unstructured tetrahedral finite element mesh.

**Comment by sslattery** [comment]
@jeff788 thanks your feedback and digging up that paper! Yes - these point cloud methods, particularly the moving least square operator require special attention for certain configurations to avoid singular least square problems hence the work I did in that paper. These originally came from the aerospace community where smooth, curved manifolds typically yielded well-behaved point configurations.

With regards to the settings you've found the most significant aspect of robustness of these algorithms that we are working on. They are incredibly simple and accurate but require a good selection of the neighborhood (i.e. the radius or the number of neighbors). Too few neighbors in a bad configuration means that you may filter out a lot of redundant points and therefore may fail on the LU decomposition in GETRF. If you're grids are fairly uniform, often the radius is a better choice of neighborhood selection. I would then start with a radius between 1 and 2 cell widths and see how that works. If they are not uniform the number of nearest neighbors is a better choice for performance reasons.

As far as your choice of algorithm I think you have a good start. If you actually want nodal data on the finite element grid then I would try interpolating on to the nodes of the tetrahedral mesh rather than the cell centers. The same goes for the structured finite difference grid. If the data is node-centered rather than cell-centered you could pass the node coordinates and nodal field values to the map as well.

**Comment by sslattery** [comment]
@jeff788 Do you mind if I ask which institution you are with and what kind of problems you are working on? We are currently developing version 3 of the code which will have OpenMP/CUDA support for advanced architectures and we are always looking for feedback from users to make improvements. Thanks!

**Comment by jeff788** [comment]
Yes, I'm at Pacific Northwest National Lab. I used DTK for a project where I coupled a subsurface reservoir simulator (PNNL's STOMP code) to a finite-element mechanics code (LLNL's GEOS). I wrote a conference paper about it and cited DTK (https://www.onepetro.org/conference-paper/ARMA-2017-0478). Now I'm trying to use it to transfer data from the same reservoir simulator, but this time to a geophysical forward modeling code with the goal of determining which geophysical monitoring techniques would be sensitive to various subsurface processes. For this application it is cell-centered data (bulk properties) that I'm transferring, which is why I'm using cell centroids as point clouds.

DTK is great, thanks for all of your work!
